# Setup
title:               Pensive
tagline:             'A thoughtful blog'
description:         'A place for thoughtful writing and reflection.'
url:                 https://venkatiyappan.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Venkat Iyappan
  url:               https://github.com/ProductAndCoffee
  email:             your-email@example.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
