# Setup
title:               Venkat Iyappan
tagline:             "Product, Coffee and GTM"
description:         'A place for thoughtful writing and reflection.'
url:                 https://productandcoffee.github.io
baseurl:             '/blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Venkat Iyappan
  url:               https://github.com/ProductAndCoffee
  email:             your-email@example.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
